### PR TITLE
Fix copy-pasta.

### PR DESCRIPTION
**Pull request by lance-edmodo**

### CODE REVIEW

**Comment by jeromebanks** [comment]
Lance, just got to looking at this.  Will merge shortly.

Can you explain changes to sessionize UDF ??

thx !!!!

**Comment by lance-edmodo** [comment]
HI-

This is not my beautiful pull request :)

I only meant to post this one change as a request:

https://github.com/lance-edmodo/brickhouse/commit/fe61db0b1be6b2e0cc5be3c7b28f1d881e7c61e1

The copy-pasta is that the Hive UDF function definitions class names
include .java and so don't work. The other changes are just my own tweaks.
We will probably make our own UDF repo with a few things we needed.

Lance

**Comment by lance-edmodo** [comment]
Also, I had to make a variant of the MD5 -> long function because when I
built this and ran it, Hive could not find the Guava classes that your MD5
class needs. Mine just uses the JDK MD5 code.

I'm mostly porting Python Streaming UDFs into Java. There's a UDF that runs
any Java Scripting language code. If this works well with Jython, I will
probably just convert our code, and our data scientists future projects, to
use Jython to run their Python inside the JVM.

https://github.com/livingsocial/HiveSwarm/blob/master/src/main/java/com/livingsocial/hive/udf/ScriptedUDF.java

I'm on Cloudera 4, with Hive 10.0, JDK 1.6. This is all scheduled for
upgrading. But until then I'm stuck with weird code.

Cheers,

Lance Norskog

**Comment by lance-edmodo** [comment]
Oh! And, I had to make a variant of the MD5 -> long UDF because when I
built this and ran it, Hive could not find the Guava classes that your MD5
class needs.  I changed the pom to include them, but this did not help.

**Comment by lance-edmodo** [comment]
Ah! Found the Guava thing. Hive 10.0 uses Guava 11.0.1. Brickhouse uses Guava 18.0. Hive does not start UDFs in their own classloader! So, even though the Brickhouse UDF jar has Guava 18.0 shaded in, the JVM still tries to run the UDF code against the Guava 11.0.2 interfaces in the Hive base binary.

A couple of methods were added to the hashing classes between these two Guava releases, and any UDF that uses hashing blows up because Guava 11.0.2 does not have them.

**Pull request closed without merging**
